[package]
name = "mosql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
derive_more = "0.99.17"
lazy_static = "1.4.0"
serde = "1.0.199"

[dependencies.mongodb]
version = "2.8.2"
default-features = false
features = ["tokio-sync"]
