[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "^0.12.0" }
serde = { version = "1", features = ["derive"] }

[lib]
name = "entity"
path = "src/mod.rs"
