{application,memento,
             [{applications,[kernel,stdlib,elixir,logger,mnesia]},
              {description,"Simple & Powerful Elixir wrapper for the Mnesia Database"},
              {modules,['Elixir.Memento','Elixir.Memento.AlreadyExistsError',
                        'Elixir.Memento.DoesNotExistError',
                        'Elixir.Memento.Error',
                        'Elixir.Memento.InvalidOperationError',
                        'Elixir.Memento.Mnesia',
                        'Elixir.Memento.MnesiaException',
                        'Elixir.Memento.NoTransactionError',
                        'Elixir.Memento.Query','Elixir.Memento.Query.Data',
                        'Elixir.Memento.Query.Spec','Elixir.Memento.Schema',
                        'Elixir.Memento.Table',
                        'Elixir.Memento.Table.Definition',
                        'Elixir.Memento.Transaction',
                        'Elixir.Memento.TransactionAborted']},
              {registered,[]},
              {vsn,"0.3.2"}]}.
