//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mapping")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub schema_id: i32,
    pub source_field_name: String,
    pub destination_field_name: String,
    pub source_field_type: String,
    pub destination_field_type: String,
    pub version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schema::Entity",
        from = "Column::SchemaId",
        to = "super::schema::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Schema,
}

impl Related<super::schema::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schema.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
