//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "schema")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub namespace: String,
    pub collection: String,
    pub sql_table: String,
    pub version: String,
    pub indexes: Option<String>,
    pub export_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::export::Entity",
        from = "Column::ExportId",
        to = "super::export::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Export,
    #[sea_orm(has_many = "super::mapping::Entity")]
    Mapping,
}

impl Related<super::export::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Export.def()
    }
}

impl Related<super::mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
